#define MAX_CLIENTES 10
#define MAX_TAM_NOMBRE_USUARIO 32
#define MAX_TAM_PAQUETE_NOMBRE_USUARIO 128
#define MAX_TAM_NOMBRE_ARCHIVO 512
#define TAM_PAQUETE 1024
#define TAM_PAQUETE_NOMBRE 64
#define BUFFER_SIZE 1024
#define MAX_USUARIOS_CONECTADOS 100