#define MAX_CLIENTES 10
#define MAX_TAM_NOMBRE_USUARIO 32
#define MAX_TAM_NOMBRE_ARCHIVO 512
#define TAM_PAQUETE 1024
#define TAM_PAQUETE_NOMBRE 64
#define MAX_USUARIOS_CONECTADOS 100
#define MAX_RESPUESTA_SERVIDOR_NOMBRE 32